### PR TITLE
Slide Down Side Menu

### PR DESCRIPTION
**Pull request by prediator**
Added slide down side menu

sidemenu
sidemenu1

### CODE REVIEW

**Comment by mattdeveluk** [comment]
Think that your pull request fucked up somehow.

**Comment by franckevva** [comment]
@prediator Your pull request is wrong. Maybe you can try again

**Comment by mattdeveluk** [comment]
@prediator Or just fork this project and push all changes.

**Comment by prediator** [comment]
thanks guys, i have forked the project
https://github.com/prediator/material-dashboard-lite-1

**Comment by alexbananabob** [comment]
@prediator, Thank you for your pull request, but it is wrong. There are many conflicts. Sorry
Obviously this is good suggestion and, perhaps, we will add this feature in the next milestone.

**Pull request closed without merging**
